# Render Infrastructure as Code for CodeVerseHub
# Reference: https://render.com/docs/infrastructure-as-code

services:
  - type: web
    name: codeversehub
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn codeversehub.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: codeversehub.settings_production
      # SECRET_KEY: set in dashboard or via blueprint diff
      # DATABASE_URL: auto-provision if using Render Postgres add-on
    autoDeploy: true
